package net.demonslayercosmetics.init;

import net.minecraft.inventory.EntityEquipmentSlot;
import net.minecraft.item.Item;
import net.demonslayercosmetics.item.ItemArmor112;
import net.demonslayercosmetics.item.ItemSword112;
import net.demonslayercosmetics.item.ItemMisc112;
import net.minecraftforge.registries.IForgeRegistry;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;

@Mod.EventBusSubscriber(modid = "demonslayercosmetics")
public class ItemInit {

    public static final Item BASIC_CAPE_CHESTPLATE = new ItemArmor112("basic_cape_chestplate", EntityEquipmentSlot.CHEST, "basic_cape_chestplate");
    public static final Item BASIC_HAORIE_CHESTPLATE = new ItemArmor112("basic_haorie_chestplate", EntityEquipmentSlot.CHEST, "basic_haorie_chestplate");
    public static final Item GENYA_OUTFIT_BOOTS = new ItemArmor112("genya_outfit_boots", EntityEquipmentSlot.FEET, "genya_outfit_boots");
    public static final Item GENYA_OUTFIT_CHESTPLATE = new ItemArmor112("genya_outfit_chestplate", EntityEquipmentSlot.CHEST, "genya_outfit_chestplate");
    public static final Item GENYA_OUTFIT_HELMET = new ItemArmor112("genya_outfit_helmet", EntityEquipmentSlot.HEAD, "genya_outfit_helmet");
    public static final Item GENYA_OUTFIT_LEGGINGS = new ItemArmor112("genya_outfit_leggings", EntityEquipmentSlot.LEGS, "genya_outfit_leggings");
    public static final Item GIYU_HAORIE_CHESTPLATE = new ItemArmor112("giyu_haorie_chestplate", EntityEquipmentSlot.CHEST, "giyu_haorie_chestplate");
    public static final Item GIYU_OUTFIT_BOOTS = new ItemArmor112("giyu_outfit_boots", EntityEquipmentSlot.FEET, "giyu_outfit_icon");
    public static final Item GIYU_OUTFIT_CHESTPLATE = new ItemArmor112("giyu_outfit_chestplate", EntityEquipmentSlot.CHEST, "giyu_outfit_icon");
    public static final Item GIYU_OUTFIT_HELMET = new ItemArmor112("giyu_outfit_helmet", EntityEquipmentSlot.HEAD, "giyu_outfit_icon");
    public static final Item GYOMEI_CAPE_CHESTPLATE = new ItemArmor112("gyomei_cape_chestplate", EntityEquipmentSlot.CHEST, "gyomei_cape_chestplate");
    public static final Item GYOMEI_OUTFIT_BOOTS = new ItemArmor112("gyomei_outfit_boots", EntityEquipmentSlot.FEET, "gyomei_outfit_icon");
    public static final Item GYOMEI_OUTFIT_CHESTPLATE = new ItemArmor112("gyomei_outfit_chestplate", EntityEquipmentSlot.CHEST, "gyomei_outfit_icon");
    public static final Item GYOMEI_OUTFIT_HELMET = new ItemArmor112("gyomei_outfit_helmet", EntityEquipmentSlot.HEAD, "gyomei_outfit_icon");
    public static final Item GYOMEI_SHIRT_CHESTPLATE = new ItemArmor112("gyomei_shirt_chestplate", EntityEquipmentSlot.CHEST, "gyomei_shirt_chestplate");
    public static final Item HASHIRA_OUTFIT_2_CHESTPLATE = new ItemArmor112("hashira_outfit_2_chestplate", EntityEquipmentSlot.CHEST, "hashira_outfit_2_chestplate");
    public static final Item HASHIRA_OUTFIT_3_CHESTPLATE = new ItemArmor112("hashira_outfit_3_chestplate", EntityEquipmentSlot.CHEST, "hashira_outfit_3_chestplate");
    public static final Item HASHIRA_OUTFIT_4_CHESTPLATE = new ItemArmor112("hashira_outfit_4_chestplate", EntityEquipmentSlot.CHEST, "hashira_outfit_4_chestplate");
    public static final Item HASHIRA_OUTFIT_5_CHESTPLATE = new ItemArmor112("hashira_outfit_5_chestplate", EntityEquipmentSlot.CHEST, "hashira_outfit_5_chestplate");
    public static final Item HASHIRA_OUTFIT_CHESTPLATE = new ItemArmor112("hashira_outfit_chestplate", EntityEquipmentSlot.CHEST, "hashira_outfit_chestplate");
    public static final Item INOSUKE_OUTFIT_BOOTS = new ItemArmor112("inosuke_outfit_boots", EntityEquipmentSlot.FEET, "inosuke_outfit_boots");
    public static final Item INOSUKE_OUTFIT_HELMET = new ItemArmor112("inosuke_outfit_helmet", EntityEquipmentSlot.HEAD, "inosuke_outfit_helmet");
    public static final Item INOSUKE_OUTFIT_LEGGINGS = new ItemArmor112("inosuke_outfit_leggings", EntityEquipmentSlot.LEGS, "inosuke_outfit_leggings");
    public static final Item KANAE_OUTFIT_BOOTS = new ItemArmor112("kanae_outfit_boots", EntityEquipmentSlot.FEET, "kanae_outfit_boots");
    public static final Item KANAE_OUTFIT_HELMET = new ItemArmor112("kanae_outfit_helmet", EntityEquipmentSlot.HEAD, "kanae_outfit_helmet");
    public static final Item KANAO_CAPE_CHESTPLATE = new ItemArmor112("kanao_cape_chestplate", EntityEquipmentSlot.CHEST, "kanao_cape_icon");
    public static final Item KANAO_OUTFIT_BOOTS = new ItemArmor112("kanao_outfit_boots", EntityEquipmentSlot.FEET, "kanao_outfit_icon");
    public static final Item KANAO_OUTFIT_CHESTPLATE = new ItemArmor112("kanao_outfit_chestplate", EntityEquipmentSlot.CHEST, "kanao_outfit_icon");
    public static final Item KANAO_OUTFIT_HELMET = new ItemArmor112("kanao_outfit_helmet", EntityEquipmentSlot.HEAD, "kanao_outfit_icon");
    public static final Item KANAO_OUTFIT_LEGGINGS = new ItemArmor112("kanao_outfit_leggings", EntityEquipmentSlot.LEGS, "kanao_outfit_icon");
    public static final Item MITSURI_HAORIE_CHESTPLATE = new ItemArmor112("mitsuri_haorie_chestplate", EntityEquipmentSlot.CHEST, "mitsuri_haorie_chestplate");
    public static final Item MITSURI_OUTFIT_BOOTS = new ItemArmor112("mitsuri_outfit_boots", EntityEquipmentSlot.FEET, "mitsuri_outfit_icon");
    public static final Item MITSURI_OUTFIT_CHESTPLATE = new ItemArmor112("mitsuri_outfit_chestplate", EntityEquipmentSlot.CHEST, "mitsuri_outfit_icon");
    public static final Item MITSURI_OUTFIT_HELMET = new ItemArmor112("mitsuri_outfit_helmet", EntityEquipmentSlot.HEAD, "mitsuri_outfit_icon");
    public static final Item MITSURI_OUTFIT_LEGGINGS = new ItemArmor112("mitsuri_outfit_leggings", EntityEquipmentSlot.LEGS, "mitsuri_outfit_icon");
    public static final Item MUICHIRO_OUTFIT_BOOTS = new ItemArmor112("muichiro_outfit_boots", EntityEquipmentSlot.FEET, "muichiro_outfit_boots");
    public static final Item MUICHIRO_OUTFIT_CHESTPLATE = new ItemArmor112("muichiro_outfit_chestplate", EntityEquipmentSlot.CHEST, "muichiro_outfit_chestplate");
    public static final Item MUICHIRO_OUTFIT_HELMET = new ItemArmor112("muichiro_outfit_helmet", EntityEquipmentSlot.HEAD, "muichiro_outfit_helmet");
    public static final Item MUICHIRO_OUTFIT_LEGGINGS = new ItemArmor112("muichiro_outfit_leggings", EntityEquipmentSlot.LEGS, "muichiro_outfit_leggings");
    public static final Item OBANAI_HAORIE_CHESTPLATE = new ItemArmor112("obanai_haorie_chestplate", EntityEquipmentSlot.CHEST, "obanai_haorie_chestplate");
    public static final Item OBANAI_OUTFIT_BOOTS = new ItemArmor112("obanai_outfit_boots", EntityEquipmentSlot.FEET, "obanai_outfit_icon");
    public static final Item OBANAI_OUTFIT_CHESTPLATE = new ItemArmor112("obanai_outfit_chestplate", EntityEquipmentSlot.CHEST, "obanai_outfit_icon");
    public static final Item OBANAI_OUTFIT_HELMET = new ItemArmor112("obanai_outfit_helmet", EntityEquipmentSlot.HEAD, "obanai_outfit_icon");
    public static final Item RENGOKU_CAPE_CHESTPLATE = new ItemArmor112("rengoku_cape_chestplate", EntityEquipmentSlot.CHEST, "rengoku_cape_chestplate");
    public static final Item RENGOKU_OUTFIT_BOOTS = new ItemArmor112("rengoku_outfit_boots", EntityEquipmentSlot.FEET, "rengoku_outfit_boots");
    public static final Item RENGOKU_OUTFIT_CHESTPLATE = new ItemArmor112("rengoku_outfit_chestplate", EntityEquipmentSlot.CHEST, "rengoku_outfit_chestplate");
    public static final Item RENGOKU_OUTFIT_HELMET = new ItemArmor112("rengoku_outfit_helmet", EntityEquipmentSlot.HEAD, "rengoku_outfit_helmet");
    public static final Item SANEMI_HAORIE_CHESTPLATE = new ItemArmor112("sanemi_haorie_chestplate", EntityEquipmentSlot.CHEST, "sanemi_haorie_chestplate");
    public static final Item SANEMI_OUTFIT_BOOTS = new ItemArmor112("sanemi_outfit_boots", EntityEquipmentSlot.FEET, "sanemi_outfit_icon");
    public static final Item SANEMI_OUTFIT_CHESTPLATE = new ItemArmor112("sanemi_outfit_chestplate", EntityEquipmentSlot.CHEST, "sanemi_outfit_icon");
    public static final Item SANEMI_OUTFIT_HELMET = new ItemArmor112("sanemi_outfit_helmet", EntityEquipmentSlot.HEAD, "sanemi_outfit_icon");
    public static final Item SANEMI_SHIRT_CHESTPLATE = new ItemArmor112("sanemi_shirt_chestplate", EntityEquipmentSlot.CHEST, "sanemi_shirt_chestplate");
    public static final Item SHINOBU_HAORIE_CHESTPLATE = new ItemArmor112("shinobu_haorie_chestplate", EntityEquipmentSlot.CHEST, "shinobu_haorie_chestplate");
    public static final Item SHINOBU_OUTFIT_BOOTS = new ItemArmor112("shinobu_outfit_boots", EntityEquipmentSlot.FEET, "shinobu_outfit_icon");
    public static final Item SHINOBU_OUTFIT_CHESTPLATE = new ItemArmor112("shinobu_outfit_chestplate", EntityEquipmentSlot.CHEST, "shinobu_outfit_icon");
    public static final Item SHINOBU_OUTFIT_HELMET = new ItemArmor112("shinobu_outfit_helmet", EntityEquipmentSlot.HEAD, "shinobu_outfit_icon");
    public static final Item STANDARD_BOOTS_BOOTS = new ItemArmor112("standard_boots_boots", EntityEquipmentSlot.FEET, "standard_uniform_icon");
    public static final Item STANDARD_OUTFIT_2_CHESTPLATE = new ItemArmor112("standard_outfit_2_chestplate", EntityEquipmentSlot.CHEST, "standard_outfit_2_chestplate");
    public static final Item STANDARD_OUTFIT_2_LEGGINGS = new ItemArmor112("standard_outfit_2_leggings", EntityEquipmentSlot.LEGS, "standard_outfit_2_leggings");
    public static final Item STANDARD_OUTFIT_3_CHESTPLATE = new ItemArmor112("standard_outfit_3_chestplate", EntityEquipmentSlot.CHEST, "standard_outfit_3_chestplate");
    public static final Item STANDARD_OUTFIT_3_LEGGINGS = new ItemArmor112("standard_outfit_3_leggings", EntityEquipmentSlot.LEGS, "standard_outfit_3_leggings");
    public static final Item STANDARD_OUTFIT_4_CHESTPLATE = new ItemArmor112("standard_outfit_4_chestplate", EntityEquipmentSlot.CHEST, "standard_outfit_4_chestplate");
    public static final Item STANDARD_OUTFIT_4_LEGGINGS = new ItemArmor112("standard_outfit_4_leggings", EntityEquipmentSlot.LEGS, "standard_outfit_4_leggings");
    public static final Item STANDARD_OUTFIT_5_CHESTPLATE = new ItemArmor112("standard_outfit_5_chestplate", EntityEquipmentSlot.CHEST, "standard_outfit_5_chestplate");
    public static final Item STANDARD_OUTFIT_5_LEGGINGS = new ItemArmor112("standard_outfit_5_leggings", EntityEquipmentSlot.LEGS, "standard_outfit_5_leggings");
    public static final Item STANDARD_OUTFIT_CHESTPLATE = new ItemArmor112("standard_outfit_chestplate", EntityEquipmentSlot.CHEST, "standard_outfit_chestplate");
    public static final Item STANDARD_OUTFIT_LEGGINGS = new ItemArmor112("standard_outfit_leggings", EntityEquipmentSlot.LEGS, "standard_outfit_leggings");
    public static final Item TANJIRO_HAORIE_CHESTPLATE = new ItemArmor112("tanjiro_haorie_chestplate", EntityEquipmentSlot.CHEST, "tanjiro_haorie_chestplate");
    public static final Item TANJIRO_OUTFIT_BOOTS = new ItemArmor112("tanjiro_outfit_boots", EntityEquipmentSlot.FEET, "tanjiro_outfit_icon");
    public static final Item TANJIRO_OUTFIT_CHESTPLATE = new ItemArmor112("tanjiro_outfit_chestplate", EntityEquipmentSlot.CHEST, "tanjiro_outfit_icon");
    public static final Item TANJIRO_OUTFIT_HELMET = new ItemArmor112("tanjiro_outfit_helmet", EntityEquipmentSlot.HEAD, "tanjiro_outfit_icon");
    public static final Item TENGEN_OUTFIT_BOOTS = new ItemArmor112("tengen_outfit_boots", EntityEquipmentSlot.FEET, "tengen_outfit_boots");
    public static final Item TENGEN_OUTFIT_CHESTPLATE = new ItemArmor112("tengen_outfit_chestplate", EntityEquipmentSlot.CHEST, "tengen_outfit_chestplate");
    public static final Item TENGEN_OUTFIT_HELMET = new ItemArmor112("tengen_outfit_helmet", EntityEquipmentSlot.HEAD, "tengen_outfit_helmet");
    public static final Item ZENITSU_HAORIE_CHESTPLATE = new ItemArmor112("zenitsu_haorie_chestplate", EntityEquipmentSlot.CHEST, "zenitsu_haorie_chestplate");
    public static final Item ZENITSU_OUTFIT_BOOTS = new ItemArmor112("zenitsu_outfit_boots", EntityEquipmentSlot.FEET, "zenitsu_outfit_icon");
    public static final Item ZENITSU_OUTFIT_CHESTPLATE = new ItemArmor112("zenitsu_outfit_chestplate", EntityEquipmentSlot.CHEST, "zenitsu_outfit_icon");
    public static final Item ZENITSU_OUTFIT_HELMET = new ItemArmor112("zenitsu_outfit_helmet", EntityEquipmentSlot.HEAD, "zenitsu_outfit_icon");

    public static final Item GENYA_SWORD = new ItemSword112("genya_sword", "genya_sword");
    public static final Item GIYU_SWORD = new ItemSword112("giyu_sword", "giyu_sword");
    public static final Item GYOMEI_AXE = new ItemSword112("gyomei_axe", "gyomei_axe");
    public static final Item GYOMEI_SPIKED_BALL = new ItemSword112("gyomei_spiked_ball", "gyomei_spiked_ball");
    public static final Item INOSUKE_SWORD = new ItemSword112("inosuke_sword", "inosuke_sword");
    public static final Item KANAE_SWORD = new ItemSword112("kanae_sword", "kanae_sword");
    public static final Item KANAO_SWORD = new ItemSword112("kanao_sword", "kanao_sword");
    public static final Item MITSURI_SWORD = new ItemSword112("mitsuri_sword", "mitsuri_sword");
    public static final Item MUICHIRO_SWORD = new ItemSword112("muichiro_sword", "muichiro_sword");
    public static final Item NICHIRIN_BLADE = new ItemSword112("nichirin_blade", "nichirin_blade");
    public static final Item OBANAI_SWORD = new ItemSword112("obanai_sword", "obanai_sword");
    public static final Item RENGOKU_SWORD = new ItemSword112("rengoku_sword", "rengoku_sword");
    public static final Item SANEMI_SWORD = new ItemSword112("sanemi_sword", "sanemi_sword");
    public static final Item SHINOBU_SWORD = new ItemSword112("shinobu_sword", "shinobu_sword");
    public static final Item TENGEN_SWORD = new ItemSword112("tengen_sword", "tengen_sword_icon");
    public static final Item ZENITSU_SWORD = new ItemSword112("zenitsu_sword", "zenitsu_sword");

    public static final Item NICHIRIN_INGOT = new ItemMisc112("nichirin_ingot", "nichirin_ingot");

    @SubscribeEvent
    public static void registerItems(RegistryEvent.Register<Item> event) {
        IForgeRegistry<Item> registry = event.getRegistry();
        registry.register(BASIC_CAPE_CHESTPLATE);
        registry.register(BASIC_HAORIE_CHESTPLATE);
        registry.register(GENYA_OUTFIT_BOOTS);
        registry.register(GENYA_OUTFIT_CHESTPLATE);
        registry.register(GENYA_OUTFIT_HELMET);
        registry.register(GENYA_OUTFIT_LEGGINGS);
        registry.register(GIYU_HAORIE_CHESTPLATE);
        registry.register(GIYU_OUTFIT_BOOTS);
        registry.register(GIYU_OUTFIT_CHESTPLATE);
        registry.register(GIYU_OUTFIT_HELMET);
        registry.register(GYOMEI_CAPE_CHESTPLATE);
        registry.register(GYOMEI_OUTFIT_BOOTS);
        registry.register(GYOMEI_OUTFIT_CHESTPLATE);
        registry.register(GYOMEI_OUTFIT_HELMET);
        registry.register(GYOMEI_SHIRT_CHESTPLATE);
        registry.register(HASHIRA_OUTFIT_2_CHESTPLATE);
        registry.register(HASHIRA_OUTFIT_3_CHESTPLATE);
        registry.register(HASHIRA_OUTFIT_4_CHESTPLATE);
        registry.register(HASHIRA_OUTFIT_5_CHESTPLATE);
        registry.register(HASHIRA_OUTFIT_CHESTPLATE);
        registry.register(INOSUKE_OUTFIT_BOOTS);
        registry.register(INOSUKE_OUTFIT_HELMET);
        registry.register(INOSUKE_OUTFIT_LEGGINGS);
        registry.register(KANAE_OUTFIT_BOOTS);
        registry.register(KANAE_OUTFIT_HELMET);
        registry.register(KANAO_CAPE_CHESTPLATE);
        registry.register(KANAO_OUTFIT_BOOTS);
        registry.register(KANAO_OUTFIT_CHESTPLATE);
        registry.register(KANAO_OUTFIT_HELMET);
        registry.register(KANAO_OUTFIT_LEGGINGS);
        registry.register(MITSURI_HAORIE_CHESTPLATE);
        registry.register(MITSURI_OUTFIT_BOOTS);
        registry.register(MITSURI_OUTFIT_CHESTPLATE);
        registry.register(MITSURI_OUTFIT_HELMET);
        registry.register(MITSURI_OUTFIT_LEGGINGS);
        registry.register(MUICHIRO_OUTFIT_BOOTS);
        registry.register(MUICHIRO_OUTFIT_CHESTPLATE);
        registry.register(MUICHIRO_OUTFIT_HELMET);
        registry.register(MUICHIRO_OUTFIT_LEGGINGS);
        registry.register(OBANAI_HAORIE_CHESTPLATE);
        registry.register(OBANAI_OUTFIT_BOOTS);
        registry.register(OBANAI_OUTFIT_CHESTPLATE);
        registry.register(OBANAI_OUTFIT_HELMET);
        registry.register(RENGOKU_CAPE_CHESTPLATE);
        registry.register(RENGOKU_OUTFIT_BOOTS);
        registry.register(RENGOKU_OUTFIT_CHESTPLATE);
        registry.register(RENGOKU_OUTFIT_HELMET);
        registry.register(SANEMI_HAORIE_CHESTPLATE);
        registry.register(SANEMI_OUTFIT_BOOTS);
        registry.register(SANEMI_OUTFIT_CHESTPLATE);
        registry.register(SANEMI_OUTFIT_HELMET);
        registry.register(SANEMI_SHIRT_CHESTPLATE);
        registry.register(SHINOBU_HAORIE_CHESTPLATE);
        registry.register(SHINOBU_OUTFIT_BOOTS);
        registry.register(SHINOBU_OUTFIT_CHESTPLATE);
        registry.register(SHINOBU_OUTFIT_HELMET);
        registry.register(STANDARD_BOOTS_BOOTS);
        registry.register(STANDARD_OUTFIT_2_CHESTPLATE);
        registry.register(STANDARD_OUTFIT_2_LEGGINGS);
        registry.register(STANDARD_OUTFIT_3_CHESTPLATE);
        registry.register(STANDARD_OUTFIT_3_LEGGINGS);
        registry.register(STANDARD_OUTFIT_4_CHESTPLATE);
        registry.register(STANDARD_OUTFIT_4_LEGGINGS);
        registry.register(STANDARD_OUTFIT_5_CHESTPLATE);
        registry.register(STANDARD_OUTFIT_5_LEGGINGS);
        registry.register(STANDARD_OUTFIT_CHESTPLATE);
        registry.register(STANDARD_OUTFIT_LEGGINGS);
        registry.register(TANJIRO_HAORIE_CHESTPLATE);
        registry.register(TANJIRO_OUTFIT_BOOTS);
        registry.register(TANJIRO_OUTFIT_CHESTPLATE);
        registry.register(TANJIRO_OUTFIT_HELMET);
        registry.register(TENGEN_OUTFIT_BOOTS);
        registry.register(TENGEN_OUTFIT_CHESTPLATE);
        registry.register(TENGEN_OUTFIT_HELMET);
        registry.register(ZENITSU_HAORIE_CHESTPLATE);
        registry.register(ZENITSU_OUTFIT_BOOTS);
        registry.register(ZENITSU_OUTFIT_CHESTPLATE);
        registry.register(ZENITSU_OUTFIT_HELMET);
        registry.register(GENYA_SWORD);
        registry.register(GIYU_SWORD);
        registry.register(GYOMEI_AXE);
        registry.register(GYOMEI_SPIKED_BALL);
        registry.register(INOSUKE_SWORD);
        registry.register(KANAE_SWORD);
        registry.register(KANAO_SWORD);
        registry.register(MITSURI_SWORD);
        registry.register(MUICHIRO_SWORD);
        registry.register(NICHIRIN_BLADE);
        registry.register(OBANAI_SWORD);
        registry.register(RENGOKU_SWORD);
        registry.register(SANEMI_SWORD);
        registry.register(SHINOBU_SWORD);
        registry.register(TENGEN_SWORD);
        registry.register(ZENITSU_SWORD);
        registry.register(NICHIRIN_INGOT);
    }
}
